version: "3.7"

services:

  app_proxy:
    environment:
      APP_HOST: seferogullari-yumlu-kripto-madencilik_dashboard_1
      APP_PORT: 8095

  db:
    image: timescale/timescaledb@sha256:981e3016a2810fec47515e3828ad70ae97b84f4c9ef63d032180b54f61566fd6
    restart: on-failure
    stop_grace_period: 1m

    environment:
      POSTGRES_DB: mkpool
      POSTGRES_USER: mkpool_user
      POSTGRES_PASSWORD: ${APP_PASSWORD}
      TIMESCALEDB_TELEMETRY: "off"

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U mkpool_user -d mkpool"]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 20s

    volumes:
      - ${APP_DATA_DIR}/data/postgres:/var/lib/postgresql/data


  mkpool:
    image: ghcr.io/usame2344/yumlu-kripto-madencilik@sha256:1c61cc8a7667f96a72148f1c7aa90efe0d4a662c2475e1f326b2accfc7795ced
    restart: on-failure
    stop_grace_period: 30s

    command:
      - /opt/yumlu/scripts/start-mkpool.sh

    depends_on:
      db:
        condition: service_healthy

    ports:
      - "3333:3333/tcp"

    environment:
      DB_HOST: seferogullari-yumlu-kripto-madencilik_db_1
      DB_PORT: "5432"
      DB_NAME: mkpool
      DB_USER: mkpool_user
      DB_PASS: ${APP_PASSWORD}

      BITCOIN_RPC_HOST: ${APP_BITCOIN_NODE_IP}
      BITCOIN_RPC_PORT: ${APP_BITCOIN_RPC_PORT}
      BITCOIN_RPC_USER: ${APP_BITCOIN_RPC_USER}
      BITCOIN_RPC_PASS: ${APP_BITCOIN_RPC_PASS}

      BITCOIN_ZMQ_HOST: ${APP_BITCOIN_NODE_IP}
      BITCOIN_ZMQ_HASHBLOCK_PORT: ${APP_BITCOIN_ZMQ_HASHBLOCK_PORT}
      BITCOIN_ZMQ_RAWBLOCK_PORT: ${APP_BITCOIN_ZMQ_RAWBLOCK_PORT}

    volumes:
      - ${APP_DATA_DIR}/data/mkpool:/data
      - ${APP_DATA_DIR}/data/runtime:/run/mkpool


  dashboard:
    image: ghcr.io/usame2344/yumlu-kripto-madencilik@sha256:1c61cc8a7667f96a72148f1c7aa90efe0d4a662c2475e1f326b2accfc7795ced
    restart: on-failure

    command:
      - /opt/yumlu/scripts/start-dashboard.sh

    depends_on:
      - mkpool

    environment:
      DB_HOST: seferogullari-yumlu-kripto-madencilik_db_1
      DB_PORT: "5432"
      DB_NAME: mkpool
      DB_USER: mkpool_user
      DB_PASS: ${APP_PASSWORD}

      MKPOOL_CTL: /opt/yumlu/mkpool-src/scripts/mkpool-ctl.py
      MKPOOL_SOCKET: /run/mkpool/mkpool.sock
      DASHBOARD_PORT: "8095"

    volumes:
      - ${APP_DATA_DIR}/data/runtime:/run/mkpool
