version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: public-pool-bch_proxy_1
      APP_PORT: 80
      PROXY_AUTH_WHITELIST: "/api/*"

  web:
    image: ghcr.io/benjamin-wilson/public-pool-ui:5f730f4@sha256:c1eaae042ee179eca87b273c04c54c8b1fba5ceb63a03411a21ec8ac6875be3d
    restart: on-failure
    stop_grace_period: 30s
    environment:
      - DOMAIN=$DEVICE_DOMAIN_NAME
      - PUBLIC_POOL_API_URL=
      - PUBLIC_POOL_STRATUM_URL=${DEVICE_DOMAIN_NAME}:3335

  server:
    image: ghcr.io/usame2344/public-pool-bch:bed7e32
    working_dir: /public-pool
    command: ["/usr/local/bin/node", "dist/main"]
    restart: on-failure
    stop_grace_period: 30s
    ports:
      - "3335:3335/tcp"
    volumes:
      - "${APP_DATA_DIR}/data/database:/public-pool/DB"
      - "/home/umbrel/public-pool-bch/.env:/public-pool/.env:ro"
    environment:
      - NODE_ENV=production
      - BITCOIN_RPC_URL=http://bitcoind
      - BITCOIN_RPC_USER=umbrel
      - BITCOIN_RPC_PORT=8332
      - BITCOIN_RPC_TIMEOUT=10000
      - API_PORT=2019
      - STRATUM_PORT=3335
      - NETWORK=mainnet
      - API_SECURE=false
      - DEV_FEE_ADDRESS=
      - POOL_IDENTIFIER=Seferogullari
    networks:
      - default
      - umbrel_main_network

  proxy:
    image: nginx:1.25.3@sha256:4c0fdaa8b6341bfdeca5f18f7837462c80cff90527ee35ef185571e1c327beac
    volumes:
      - ${APP_DATA_DIR}/data/proxy/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - web
      - server
    restart: on-failure

networks:
  umbrel_main_network:
    external: true
    name: umbrel_main_network
